### PR TITLE
Add arrow49

### PR DESCRIPTION
**Pull request by thomas-k-cameron**
Add arrow-49.

Some libraries like polars use arrow-49, it really helps if you could merge this PR for me.

### CODE REVIEW

**Comment by thomas-k-cameron** [comment]
Sorry, I thought I was making this PR for my own repo but it seems like I made a mistake.

I will keep it open in a draft state. Let me come back to you later.

**Comment by chmp** [comment]
Hey. After being blocked for some time, I will finally get back to finish the serde_arrow 0.9 release. As part of this release, I will also add arrow 49 support. See #102 .

**Comment by chmp** [comment]
Arrow=49 now supported in main.

**Comment by thomas-k-cameron** [comment]
@chmp 
Thank you!

**Pull request closed without merging**
